# Generated by Django 3.2.5 on 2021-08-04 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerSupport', '0005_auto_20210804_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
