# Generated by Django 3.2.5 on 2021-08-04 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerSupport', '0006_alter_ticket_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
