# Generated by Django 3.2.5 on 2021-08-05 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerSupport', '0008_ticket_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['datetime']},
        ),
    ]
