# Generated by Django 3.2.5 on 2021-08-05 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerSupport', '0011_alter_ticket_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['datetime', 'created_date_and_time']},
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='created_date',
            new_name='created_date_and_time',
        ),
    ]
