# Generated by Django 3.2.5 on 2021-08-05 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerSupport', '0013_auto_20210805_1446'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['date_and_time_for_callback', 'submited_date_and_time']},
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='created_date_and_time',
            new_name='submited_date_and_time',
        ),
    ]
