# Generated by Django 3.2.5 on 2021-08-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerSupport', '0014_auto_20210805_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('CustomerSupport.ticket',),
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_archive',
            field=models.BooleanField(default=False),
        ),
    ]
