# Generated by Django 3.2.5 on 2021-08-05 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerSupport', '0015_auto_20210805_1501'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TicketProxy',
        ),
        migrations.CreateModel(
            name='TicketsArchive',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('CustomerSupport.ticket',),
        ),
    ]
