# Generated by Django 3.2.5 on 2021-08-05 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerSupport', '0017_auto_20210805_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='is_archive',
            new_name='archive',
        ),
    ]
