# Generated by Django 3.2.5 on 2021-08-05 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerSupport', '0018_rename_is_archive_ticket_archive'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArchivedTicket',
        ),
        migrations.CreateModel(
            name='ArchivedTicket',
            fields=[
                ('ticket_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='CustomerSupport.ticket')),
            ],
            options={
                'proxy': False,
            },
            bases=('CustomerSupport.ticket',),
        ),
    ]
